// AUTO-GENERATED by scripts/generate-backgrounds.mjs — do not edit by hand.
// Ported from PatternCraft (https://github.com/megh-bari/pattern-craft).
import type { CSSProperties } from "react";

/** Every EffectBackground pattern id, in source order. */
export const effectBackgroundVariants = [
  "aurora-dream-corner-whispers",
  "aurora-dream-soft-harmony",
  "aurora-dream-diagonal-flow",
  "aurora-dream-vivid-bloom",
  "dreamy-sky-pink-glow",
  "peachy-mint-dream",
  "soft-pastel-dream",
  "dreamy-sunset-gradient",
  "soft-morning-mist",
  "peachy-sunrise-glow",
  "mint-fresh-breeze",
  "cotton-candy-sky",
  "cotton-candy-sky-reverse",
  "spring-meadow-mist",
  "ocean-breeze-fade",
  "lavender-blush-left-flow",
  "lavender-blush-right-flow",
  "minty-cloud-drift",
  "rose-gold-whisper",
  "aurora-silk-fade",
  "beige-texture",
  "soft-warm-pastel-texture",
  "warm-light-apricot-coral",
  "warm-pastel-coral-cream",
  "soft-yellow-glow",
  "soft-dark-yellow-glow",
  "orange-soft-glow",
  "soft-green-glow",
  "purple-center-glow",
  "green-center-glow",
  "indigo-center-glow",
  "lime-center-glow",
  "sunrise-glow",
  "soft lavender-center-glow",
  "soft-pink-glow",
  "light-sky-blue-glow",
  "sunny-glow",
  "purple-glow-bg",
  "teal-glow-bg",
  "warm-orange-glow-bg",
  "cool-blue-glow-bg",
  "purple-glow-bg-left",
  "teal-glow-bg-left",
  "warm-orange-glow-bg-left",
  "cool-blue-glow-bg-left",
  "purple-glow-bg-top",
  "teal-glow-bg-top",
  "warm-orange-glow-bg-top",
  "cool-blue-glow-bg-top",
  "crystal-maze",
  "moonlit-fog",
  "pastel-wave",
  "soft-blue-radial",
  "morning-haze",
  "midnight-mist",
  "aurora-mystic-mist",
  "tropical-dusk-glow",
  "ember-glow",
  "cosmic-aurora",
  "midnight-ember",
  "deep-ocean-glow",
  "cosmic-noise",
  "volcanic-ember",
  "crimson-core-glow",
  "northern-aurora",
  "cosmic-sparkle",
] as const;

export type EffectBackgroundVariant = (typeof effectBackgroundVariants)[number];

/** The full inline style for each EffectBackground variant. */
export const effectBackgroundPresets: Record<
  EffectBackgroundVariant,
  CSSProperties
> = {
  "aurora-dream-corner-whispers": {
    backgroundImage:
      "\n       radial-gradient(ellipse 85% 65% at 8% 8%, rgba(175, 109, 255, 0.42), transparent 60%),\n            radial-gradient(ellipse 75% 60% at 75% 35%, rgba(255, 235, 170, 0.55), transparent 62%),\n            radial-gradient(ellipse 70% 60% at 15% 80%, rgba(255, 100, 180, 0.40), transparent 62%),\n            radial-gradient(ellipse 70% 60% at 92% 92%, rgba(120, 190, 255, 0.45), transparent 62%),\n            linear-gradient(180deg, #f7eaff 0%, #fde2ea 100%)\n    ",
    backgroundSize: "100% 100%",
    backgroundColor: "#f7eaff",
  },
  "aurora-dream-soft-harmony": {
    backgroundImage:
      "\n      radial-gradient(ellipse 80% 60% at 60% 20%, rgba(175, 109, 255, 0.50), transparent 65%),\n        radial-gradient(ellipse 70% 60% at 20% 80%, rgba(255, 100, 180, 0.45), transparent 65%),\n        radial-gradient(ellipse 60% 50% at 60% 65%, rgba(255, 235, 170, 0.43), transparent 62%),\n        radial-gradient(ellipse 65% 40% at 50% 60%, rgba(120, 190, 255, 0.48), transparent 68%),\n        linear-gradient(180deg, #f7eaff 0%, #fde2ea 100%)\n    ",
    backgroundSize: "100% 100%",
    backgroundColor: "#f7eaff",
  },
  "aurora-dream-diagonal-flow": {
    backgroundImage:
      "\n       radial-gradient(ellipse 80% 60% at 5% 40%, rgba(175, 109, 255, 0.48), transparent 67%),\n        radial-gradient(ellipse 70% 60% at 45% 45%, rgba(255, 100, 180, 0.41), transparent 67%),\n        radial-gradient(ellipse 62% 52% at 83% 76%, rgba(255, 235, 170, 0.44), transparent 63%),\n        radial-gradient(ellipse 60% 48% at 75% 20%, rgba(120, 190, 255, 0.36), transparent 66%),\n        linear-gradient(45deg, #f7eaff 0%, #fde2ea 100%)\n    ",
    backgroundSize: "100% 100%",
    backgroundColor: "#f7eaff",
  },
  "aurora-dream-vivid-bloom": {
    backgroundImage:
      "\n      radial-gradient(ellipse 80% 60% at 70% 20%, rgba(175, 109, 255, 0.85), transparent 68%),\n      radial-gradient(ellipse 70% 60% at 20% 80%, rgba(255, 100, 180, 0.75), transparent 68%),\n      radial-gradient(ellipse 60% 50% at 60% 65%, rgba(255, 235, 170, 0.98), transparent 68%),\n      radial-gradient(ellipse 65% 40% at 50% 60%, rgba(120, 190, 255, 0.3), transparent 68%),\n      linear-gradient(180deg, #f7eaff 0%, #fde2ea 100%)\n    ",
    backgroundSize: "100% 100%",
    backgroundColor: "#f7eaff",
  },
  "dreamy-sky-pink-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at 30% 70%, rgba(173, 216, 230, 0.35), transparent 60%), /* soft blue */\n      radial-gradient(circle at 70% 30%, rgba(255, 182, 193, 0.4), transparent 60%)  /* soft pink */\n    ",
    backgroundColor: "#fefcff",
  },
  "peachy-mint-dream": {
    background:
      "linear-gradient(135deg, #FFB5A7 0%, #F8D7DA 25%, #E8F5E8 75%, #B8F2D0 100%)",
  },
  "soft-pastel-dream": {
    background:
      "linear-gradient(135deg, #F8BBD9 0%, #FDD5B4 25%, #FFF2CC 50%, #E1F5FE 75%, #BBDEFB 100%)",
  },
  "dreamy-sunset-gradient": {
    backgroundImage:
      "\n      linear-gradient(180deg, \n        rgba(245,245,220,1) 0%, \n        rgba(255,223,186,0.8) 25%, \n        rgba(255,182,193,0.6) 50%, \n        rgba(147,112,219,0.7) 75%, \n        rgba(72,61,139,0.9) 100%\n      ),\n      radial-gradient(circle at 30% 20%, rgba(255,255,224,0.4) 0%, transparent 50%),\n      radial-gradient(circle at 70% 80%, rgba(72,61,139,0.6) 0%, transparent 70%),\n      radial-gradient(circle at 50% 60%, rgba(147,112,219,0.3) 0%, transparent 60%)\n    ",
    backgroundColor: "#f5f5dc",
  },
  "soft-morning-mist": {
    backgroundImage:
      "\n      linear-gradient(135deg, \n        rgba(248,250,252,1) 0%, \n        rgba(219,234,254,0.7) 30%, \n        rgba(165,180,252,0.5) 60%, \n        rgba(129,140,248,0.6) 100%\n      ),\n      radial-gradient(circle at 20% 30%, rgba(255,255,255,0.6) 0%, transparent 40%),\n      radial-gradient(circle at 80% 70%, rgba(199,210,254,0.4) 0%, transparent 50%),\n      radial-gradient(circle at 40% 80%, rgba(224,231,255,0.3) 0%, transparent 60%)\n    ",
    backgroundColor: "#f8fafc",
  },
  "peachy-sunrise-glow": {
    backgroundImage:
      "\n      linear-gradient(180deg, \n        rgba(255,247,237,1) 0%, \n        rgba(255,237,213,0.8) 25%, \n        rgba(254,215,170,0.6) 50%, \n        rgba(251,146,60,0.4) 75%, \n        rgba(249,115,22,0.3) 100%\n      ),\n      radial-gradient(circle at 20% 80%, rgba(255,255,255,0.6) 0%, transparent 40%),\n      radial-gradient(circle at 80% 20%, rgba(254,215,170,0.5) 0%, transparent 50%),\n      radial-gradient(circle at 60% 60%, rgba(252,165,165,0.3) 0%, transparent 45%)\n    ",
    backgroundColor: "#fff7ed",
  },
  "mint-fresh-breeze": {
    backgroundImage:
      "\n      linear-gradient(45deg, \n        rgba(240,253,250,1) 0%, \n        rgba(204,251,241,0.7) 30%, \n        rgba(153,246,228,0.5) 60%, \n        rgba(94,234,212,0.4) 100%\n      ),\n      radial-gradient(circle at 40% 30%, rgba(255,255,255,0.8) 0%, transparent 40%),\n      radial-gradient(circle at 80% 70%, rgba(167,243,208,0.5) 0%, transparent 50%),\n      radial-gradient(circle at 20% 80%, rgba(209,250,229,0.6) 0%, transparent 45%)\n    ",
    backgroundColor: "#f0fdfa",
  },
  "cotton-candy-sky": {
    background:
      "linear-gradient(45deg, #FFB3D9 0%, #FFD1DC 20%, #FFF0F5 40%, #E6F3FF 60%, #D1E7FF 80%, #C7E9F1 100%)",
  },
  "cotton-candy-sky-reverse": {
    background:
      "linear-gradient(225deg, #FFB3D9 0%, #FFD1DC 20%, #FFF0F5 40%, #E6F3FF 60%, #D1E7FF 80%, #C7E9F1 100%)",
  },
  "spring-meadow-mist": {
    background:
      "linear-gradient(90deg, #D4F1C5 0%, #E8F5E8 20%, #F0F8E8 40%, #FFF9E6 60%, #FFE5B4 80%, #FFDAB9 100%)",
  },
  "ocean-breeze-fade": {
    background:
      "linear-gradient(225deg, #B3E5FC 0%, #E0F2F1 25%, #F0F4C3 50%, #FFF8E1 75%, #FFECB3 100%)",
  },
  "lavender-blush-left-flow": {
    background:
      "linear-gradient(315deg, #E1BEE7 0%, #F3E5F5 20%, #FCE4EC 40%, #FFF0F5 60%, #F8BBD9 80%, #E1BEE7 100%)",
  },
  "lavender-blush-right-flow": {
    background:
      "linear-gradient(135deg, #E1BEE7 0%, #F3E5F5 20%, #FCE4EC 40%, #FFF0F5 60%, #F8BBD9 80%, #E1BEE7 100%)",
  },
  "minty-cloud-drift": {
    background:
      "linear-gradient(120deg, #C8E6C9 0%, #DCEDC8 20%, #F1F8E9 40%, #FFFDE7 60%, #FFF9C4 80%, #F0F4C3 100%)",
  },
  "rose-gold-whisper": {
    background:
      "linear-gradient(270deg, #FFECB3 0%, #FFE0B2 20%, #FFCDD2 40%, #F8BBD9 60%, #E1BEE7 80%, #D1C4E9 100%)",
  },
  "aurora-silk-fade": {
    background:
      "linear-gradient(150deg, #B39DDB 0%, #D1C4E9 20%, #F3E5F5 40%, #FCE4EC 60%, #FFCDD2 80%, #FFAB91 100%)",
  },
  "beige-texture": {
    backgroundImage:
      "\n        radial-gradient(circle at 20% 80%, rgba(120,119,198,0.3) 0%, transparent 50%),\n        radial-gradient(circle at 80% 20%, rgba(255,255,255,0.5) 0%, transparent 50%),\n        radial-gradient(circle at 40% 40%, rgba(120,119,198,0.1) 0%, transparent 50%)\n      ",
    backgroundColor: "#f5f5dc",
  },
  "soft-warm-pastel-texture": {
    backgroundImage:
      "\n      radial-gradient(circle at 20% 80%, rgba(255, 182, 153, 0.3) 0%, transparent 50%),  /* soft peach */\n      radial-gradient(circle at 80% 20%, rgba(255, 244, 214, 0.5) 0%, transparent 50%),  /* pale buttery yellow */\n      radial-gradient(circle at 40% 40%, rgba(255, 182, 153, 0.1) 0%, transparent 50%)   /* lighter peach */\n    ",
    backgroundColor: "#fff8f0",
  },
  "warm-light-apricot-coral": {
    backgroundImage:
      "\n      radial-gradient(circle at 20% 80%, rgba(255, 220, 190, 0.3) 0%, transparent 50%),  /* soft apricot */\n      radial-gradient(circle at 80% 20%, rgba(255, 245, 238, 0.35) 0%, transparent 50%), /* pale coral cream */\n      radial-gradient(circle at 40% 40%, rgba(255, 210, 180, 0.15) 0%, transparent 50%)  /* light coral */\n    ",
    backgroundColor: "#fff9f5",
  },
  "warm-pastel-coral-cream": {
    backgroundImage:
      "\n      radial-gradient(circle at 20% 80%, rgba(255, 160, 146, 0.25) 0%, transparent 50%),  /* soft coral */\n      radial-gradient(circle at 80% 20%, rgba(255, 244, 228, 0.3) 0%, transparent 50%),  /* pale cream */\n      radial-gradient(circle at 40% 40%, rgba(255, 160, 146, 0.15) 0%, transparent 50%)  /* lighter coral */\n    ",
    backgroundColor: "#fef9f7",
  },
  "soft-yellow-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at center, #FFF991 0%, transparent 70%)\n    ",
    opacity: 0.6,
    mixBlendMode: "multiply",
  },
  "soft-dark-yellow-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at center, #ccb755 0%, transparent 70%)\n    ",
    opacity: 0.6,
    mixBlendMode: "multiply",
  },
  "orange-soft-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at center, #FF7112, transparent)\n    ",
    opacity: 0.3,
    mixBlendMode: "multiply",
  },
  "soft-green-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at center, #8FFFB0, transparent)\n    ",
  },
  "purple-center-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #8249fc, transparent)        \n   ",
    backgroundColor: "#ffffff",
  },
  "green-center-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #10b981, transparent)\n   ",
    backgroundSize: "100% 100%",
    backgroundColor: "#ffffff",
  },
  "indigo-center-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #6366f1, transparent)\n   ",
    backgroundColor: "#ffffff",
  },
  "lime-center-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #84cc16, transparent)\n   ",
    backgroundColor: "#ffffff",
  },
  "sunrise-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #eab308, transparent)\n   ",
    backgroundColor: "#ffffff",
  },
  "soft lavender-center-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #c4b5fd, transparent)\n   ",
    backgroundColor: "#ffffff",
  },
  "soft-pink-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #fbb6ce, transparent)\n   ",
    backgroundColor: "#ffffff",
  },
  "light-sky-blue-glow": {
    backgroundImage:
      "\n     radial-gradient(circle at center, #93c5fd, transparent)\n   ",
    backgroundColor: "#ffffff",
  },
  "sunny-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at center, #fde047, transparent)\n    ",
    backgroundColor: "#fffbe8",
  },
  "purple-glow-bg": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top right,\n        rgba(173, 109, 244, 0.5),\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "teal-glow-bg": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top right,\n        rgba(56, 193, 182, 0.5),  /* teal color */\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "warm-orange-glow-bg": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top right,\n        rgba(255, 140, 60, 0.5),  /* warm orange */\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "cool-blue-glow-bg": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top right,\n        rgba(70, 130, 180, 0.5),  /* steel blue */\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "purple-glow-bg-left": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top left,\n        rgba(173, 109, 244, 0.5),\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "teal-glow-bg-left": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top left,\n        rgba(56, 193, 182, 0.5),  /* teal color */\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "warm-orange-glow-bg-left": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top left,\n        rgba(255, 140, 60, 0.5),  /* warm orange */\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "cool-blue-glow-bg-left": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top left,\n        rgba(70, 130, 180, 0.5),  /* steel blue */\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "purple-glow-bg-top": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top center,\n        rgba(173, 109, 244, 0.5),\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "teal-glow-bg-top": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top center,\n        rgba(56, 193, 182, 0.5),\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "warm-orange-glow-bg-top": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top center,\n        rgba(255, 140, 60, 0.5),\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "cool-blue-glow-bg-top": {
    backgroundImage:
      "\n      radial-gradient(\n        circle at top center,\n        rgba(70, 130, 180, 0.5),\n        transparent 70%\n      )\n    ",
    filter: "blur(80px)",
    backgroundRepeat: "no-repeat",
    backgroundColor: "#ffffff",
  },
  "crystal-maze": {
    background:
      "\n        repeating-linear-gradient(\n          60deg,\n          transparent 0px,\n          transparent 1px,\n          rgba(255, 255, 255, 0.05) 1px,\n          rgba(255, 255, 255, 0.05) 2px\n        ),\n        repeating-linear-gradient(\n          -60deg,\n          transparent 0px,\n          transparent 1px,\n          rgba(255, 255, 255, 0.05) 1px,\n          rgba(255, 255, 255, 0.05) 2px\n        ),\n        linear-gradient(\n          60deg,\n          rgba(43, 108, 176, 0.4) 0%,\n          rgba(72, 126, 176, 0.4) 33%,\n          rgba(95, 142, 176, 0.4) 66%,\n          rgba(116, 157, 176, 0.4) 100%\n        ),\n        radial-gradient(\n          circle at 50% 50%,\n          rgba(255, 255, 255, 0.2) 0%,\n          transparent 50%\n        )\n      ",
    backgroundBlendMode: "overlay, overlay, normal, screen",
  },
  "moonlit-fog": {
    background:
      "\n        radial-gradient(circle at 70% 30%, rgba(255, 255, 255, 0.1) 0%, transparent 50%),\n        radial-gradient(circle at 30% 70%, rgba(176, 196, 222, 0.15) 0%, transparent 50%),\n        linear-gradient(135deg, \n          #2c3e50 0%,\n          #3a506b 25%,\n          #435e79 50%,\n          #516b87 75%,\n          #5f7995 100%\n        )\n      ",
    backgroundBlendMode: "soft-light, screen, normal",
    filter: "brightness(1.05) contrast(1.05)",
  },
  "pastel-wave": {
    background:
      "linear-gradient(120deg, #d5c5ff 0%, #a7f3d0 50%, #f0f0f0 100%)",
  },
  "soft-blue-radial": {
    backgroundImage:
      "\n     radial-gradient(circle at top center, rgba(59, 130, 246, 0.5), transparent 70%)\n   ",
    backgroundSize: "100% 100%",
    backgroundColor: "#ffffff",
  },
  "morning-haze": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 100%, rgba(253, 224, 71, 0.4) 0%, transparent 60%),\n        radial-gradient(circle at 50% 100%, rgba(251, 191, 36, 0.4) 0%, transparent 70%),\n        radial-gradient(circle at 50% 100%, rgba(244, 114, 182, 0.5) 0%, transparent 80%)\n      ",
    backgroundColor: "#ffffff",
  },
  "midnight-mist": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 100%, rgba(70, 85, 110, 0.5) 0%, transparent 60%),\n        radial-gradient(circle at 50% 100%, rgba(99, 102, 241, 0.4) 0%, transparent 70%),\n        radial-gradient(circle at 50% 100%, rgba(181, 184, 208, 0.3) 0%, transparent 80%)\n      ",
    backgroundColor: "#000000",
  },
  "aurora-mystic-mist": {
    backgroundImage:
      "\n      radial-gradient(circle at 50% 100%, rgba(58, 175, 169, 0.6) 0%, transparent 60%),\n      radial-gradient(circle at 50% 100%, rgba(255, 140, 0, 0.4) 0%, transparent 70%),\n      radial-gradient(circle at 50% 100%, rgba(238, 130, 238, 0.3) 0%, transparent 80%)\n    ",
    backgroundColor: "#000000",
  },
  "tropical-dusk-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at 50% 100%, rgba(255, 99, 71, 0.6) 0%, transparent 60%), /* tomato red */\n      radial-gradient(circle at 50% 100%, rgba(255, 215, 0, 0.4) 0%, transparent 70%), /* gold */\n      radial-gradient(circle at 50% 100%, rgba(60, 179, 113, 0.3) 0%, transparent 80%) /* medium sea green */\n    ",
    backgroundColor: "#000000",
  },
  "ember-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at 50% 100%, rgba(255, 69, 0, 0.6) 0%, transparent 60%), /* orange red */\n      radial-gradient(circle at 50% 100%, rgba(255, 140, 0, 0.4) 0%, transparent 70%), /* dark orange */\n      radial-gradient(circle at 50% 100%, rgba(255, 215, 0, 0.3) 0%, transparent 80%) /* gold */\n    ",
    backgroundColor: "#000000",
  },
  "cosmic-aurora": {
    backgroundImage:
      "\n        radial-gradient(ellipse at 20% 30%, rgba(56, 189, 248, 0.4) 0%, transparent 60%),\n        radial-gradient(ellipse at 80% 70%, rgba(139, 92, 246, 0.3) 0%, transparent 70%),\n        radial-gradient(ellipse at 60% 20%, rgba(236, 72, 153, 0.25) 0%, transparent 50%),\n        radial-gradient(ellipse at 40% 80%, rgba(34, 197, 94, 0.2) 0%, transparent 65%)\n      ",
    backgroundColor: "#0a0a0a",
  },
  "midnight-ember": {
    background:
      "radial-gradient(ellipse at center, #3d2914 0%, #2a1810 30%, #1a0f0a 60%, #0d0806 100%)",
  },
  "deep-ocean-glow": {
    background:
      "radial-gradient(70% 55% at 50% 50%, #2a5d77 0%, #184058 18%, #0f2a43 34%, #0a1b30 50%, #071226 66%, #040d1c 80%, #020814 92%, #01040d 97%, #000309 100%), radial-gradient(160% 130% at 10% 10%, rgba(0,0,0,0) 38%, #000309 76%, #000208 100%), radial-gradient(160% 130% at 90% 90%, rgba(0,0,0,0) 38%, #000309 76%, #000208 100%)",
  },
  "cosmic-noise": {
    background:
      "radial-gradient(circle at 20% 20%, rgba(255,255,255,0.08) 0%, transparent 40%), radial-gradient(circle at 80% 30%, rgba(255,255,255,0.05) 0%, transparent 40%), linear-gradient(120deg, #0f0e17 0%, #1a1b26 100%)",
  },
  "volcanic-ember": {
    background:
      "\n      radial-gradient(ellipse 120% 70% at 70% 80%, rgba(87, 24, 69, 0.20), transparent 52%),\n      radial-gradient(ellipse 160% 45% at 30% 30%, rgba(153, 27, 27, 0.16), transparent 58%),\n      radial-gradient(ellipse 85% 100% at 10% 60%, rgba(69, 26, 3, 0.22), transparent 46%),\n      #1c1917\n    ",
  },
  "crimson-core-glow": {
    background:
      "linear-gradient(0deg, rgba(0,0,0,0.6), rgba(0,0,0,0.6)), radial-gradient(68% 58% at 50% 50%, #c81e3a 0%, #a51d35 16%, #7d1a2f 32%, #591828 46%, #3c1722 60%, #2a151d 72%, #1f1317 84%, #141013 94%, #0a0a0a 100%), radial-gradient(90% 75% at 50% 50%, rgba(228,42,66,0.06) 0%, rgba(228,42,66,0) 55%), radial-gradient(150% 120% at 8% 8%, rgba(0,0,0,0) 42%, #0b0a0a 82%, #070707 100%), radial-gradient(150% 120% at 92% 92%, rgba(0,0,0,0) 42%, #0b0a0a 82%, #070707 100%), radial-gradient(60% 50% at 50% 60%, rgba(240,60,80,0.06), rgba(0,0,0,0) 60%), #050505",
  },
  "northern-aurora": {
    background:
      "\n        radial-gradient(ellipse 70% 55% at 50% 50%, rgba(255, 20, 147, 0.15), transparent 50%),\n            radial-gradient(ellipse 160% 130% at 10% 10%, rgba(0, 255, 255, 0.12), transparent 60%),\n            radial-gradient(ellipse 160% 130% at 90% 90%, rgba(138, 43, 226, 0.18), transparent 65%),\n            radial-gradient(ellipse 110% 50% at 80% 30%, rgba(255, 215, 0, 0.08), transparent 40%),\n            #000000\n      ",
  },
  "cosmic-sparkle": {
    background:
      "\n        radial-gradient(circle at 50% 50%, rgba(255, 0, 255, 0.08) 0%, transparent 45%),\n        radial-gradient(circle at 50% 50%, rgba(0, 255, 255, 0.08) 10%, transparent 55%),\n        radial-gradient(circle at 50% 50%, #111 0%, #1a1a1a 100%)\n      ",
    backgroundBlendMode: "soft-light",
    boxShadow:
      "inset 0 0 60px rgba(255, 255, 255, 0.3),\n        inset 20px 0 80px rgba(255, 0, 255, 0.2),\n        inset -20px 0 80px rgba(0, 255, 255, 0.2),\n        inset 20px 0 300px rgba(255, 0, 255, 0.1),\n        inset -20px 0 300px rgba(0, 255, 255, 0.1),\n        0 0 50px rgba(255, 255, 255, 0.1),\n        -10px 0 80px rgba(255, 0, 255, 0.1),\n        10px 0 80px rgba(0, 255, 255, 0.1)",
    filter: "contrast(1.05) brightness(1.05) blur(0.5px)",
  },
};
