// AUTO-GENERATED by scripts/generate-backgrounds.mjs — do not edit by hand.
// Ported from PatternCraft (https://github.com/megh-bari/pattern-craft).
import type { CSSProperties } from "react";

/** Every GradientBackground pattern id, in source order. */
export const gradientBackgroundVariants = [
  "dark-radial-glow",
  "blue-radial-glow",
  "purple-radial-glow",
  "cyan-radial-glow",
  "orange-radial-glow",
  "pink-radial-glow",
  "gold-radial-glow",
  "red-radial-glow",
  "lime-radial-glow",
  "emerald-radial-glow",
  "aurora-waves",
  "aurora-midnight-glow",
  "crimson-shadow-glow",
  "emerald-depths-glow",
  "violet-storm-glow",
  "golden-horizon-glow",
  "ocean-abyss-glow",
  "rose-twilight-glow",
  "copper-forge-glow",
  "arctic-lights-glow",
  "indigo-cosmos-glow",
  "pearl-mist-glow",
  "magenta-nebula-glow",
  "pink-aurora-top",
  "midnight-aurora-glow",
  "midnight-radial-glow",
  "deep-navy-gold",
  "rich-burgundy",
  "forest-emerald",
  "royal-purple",
  "copper-bronze",
  "steel-blue",
  "warm-amber",
  "moonlight-silver",
  "center-spotlight-white",
  "center-spotlight-blue",
  "center-spotlight-emerald",
  "center-spotlight-crimson",
  "center-spotlight-violet",
  "center-spotlight-amber",
  "center-spotlight-cyan",
  "center-spotlight-rose",
  "center-spotlight",
  "top-spotlight",
  "aurora-edge-glow",
  "prismatic-aurora-burst",
  "cosmic-nebula",
  "stellar-mist",
] as const;

export type GradientBackgroundVariant =
  (typeof gradientBackgroundVariants)[number];

/** The full inline style for each GradientBackground variant. */
export const gradientBackgroundPresets: Record<
  GradientBackgroundVariant,
  CSSProperties
> = {
  "dark-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 200px, #3e3e3e, transparent)",
    backgroundColor: "#020617",
  },
  "blue-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 600px at 50% 50%, rgba(59,130,246,0.3), transparent)",
    backgroundColor: "#0f172a",
  },
  "purple-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(139,92,246,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "cyan-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(6,182,212,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "orange-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(249,115,22,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "pink-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(236,72,153,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "gold-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(251,191,36,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "red-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(239,68,68,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "lime-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 100px, rgba(132,204,22,0.4), transparent)",
    backgroundColor: "#020617",
  },
  "emerald-radial-glow": {
    backgroundImage:
      "radial-gradient(circle 500px at 50% 300px, rgba(16,185,129,0.35), transparent)",
    backgroundColor: "#020617",
  },
  "aurora-waves": {
    background:
      "linear-gradient(45deg, #1a1a1a 0%, #003366 100%),\n        repeating-linear-gradient(\n          45deg,\n          rgba(0, 255, 255, 0.1) 0px,\n          rgba(0, 255, 255, 0.1) 20px,\n          rgba(0, 255, 0, 0.1) 20px,\n          rgba(0, 255, 0, 0.1) 40px\n        ),\n        radial-gradient(\n          circle at 50% 50%,\n          rgba(32, 196, 232, 0.3) 0%,\n          rgba(76, 201, 240, 0.1) 100%\n        )",
    backgroundBlendMode: "normal, overlay, overlay",
  },
  "aurora-midnight-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(120, 180, 255, 0.25), transparent 70%), #000000",
  },
  "crimson-shadow-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(255, 80, 120, 0.25), transparent 70%), #000000",
  },
  "emerald-depths-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(16, 185, 129, 0.25), transparent 70%), #000000",
  },
  "violet-storm-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(139, 92, 246, 0.25), transparent 70%), #000000",
  },
  "golden-horizon-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(251, 191, 36, 0.25), transparent 70%), #000000",
  },
  "ocean-abyss-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(6, 182, 212, 0.25), transparent 70%), #000000",
  },
  "rose-twilight-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(244, 114, 182, 0.25), transparent 70%), #000000",
  },
  "copper-forge-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(249, 115, 22, 0.25), transparent 70%), #000000",
  },
  "arctic-lights-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(34, 197, 94, 0.25), transparent 70%), #000000",
  },
  "indigo-cosmos-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(99, 102, 241, 0.25), transparent 70%), #000000",
  },
  "pearl-mist-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(226, 232, 240, 0.15), transparent 70%), #000000",
  },
  "magenta-nebula-glow": {
    background:
      "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(236, 72, 153, 0.25), transparent 70%), #000000",
  },
  "pink-aurora-top": {
    backgroundImage:
      "\n     radial-gradient(\n       circle at top,\n       rgba(255, 255, 255, 0.08) 0%,\n       rgba(255, 140, 250, 0.08) 20%,\n       rgba(0, 0, 0, 0.0) 60%\n     )\n   ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "midnight-aurora-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at 50% 50%, \n        rgba(58, 123, 255, 0.25) 0%,       /* Electric Blue */\n        rgba(100, 149, 237, 0.15) 25%,    /* Cornflower Blue */\n        rgba(123, 104, 238, 0.07) 35%,    /* Medium Slate Blue */\n        transparent 50%\n      )\n    ",
    backgroundColor: "#000000",
  },
  "midnight-radial-glow": {
    backgroundImage:
      "\n      radial-gradient(circle at 50% 50%, \n        rgba(226, 232, 240, 0.2) 0%, \n        rgba(226, 232, 240, 0.1) 25%, \n        rgba(226, 232, 240, 0.05) 35%, \n        transparent 50%\n      )\n    ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "deep-navy-gold": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(251, 191, 36, 0.15) 0%, \n          rgba(251, 191, 36, 0.08) 25%, \n          rgba(251, 191, 36, 0.03) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#0f172a",
  },
  "rich-burgundy": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(220, 38, 38, 0.2) 0%, \n          rgba(220, 38, 38, 0.12) 25%, \n          rgba(220, 38, 38, 0.06) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#1c1917",
  },
  "forest-emerald": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(34, 197, 94, 0.18) 0%, \n          rgba(34, 197, 94, 0.1) 25%, \n          rgba(34, 197, 94, 0.04) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#111827",
  },
  "royal-purple": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(147, 51, 234, 0.2) 0%, \n          rgba(147, 51, 234, 0.12) 25%, \n          rgba(147, 51, 234, 0.05) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#18181b",
  },
  "copper-bronze": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(194, 65, 12, 0.18) 0%, \n          rgba(194, 65, 12, 0.1) 25%, \n          rgba(194, 65, 12, 0.04) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#1c1917",
  },
  "steel-blue": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(59, 130, 246, 0.16) 0%, \n          rgba(59, 130, 246, 0.09) 25%, \n          rgba(59, 130, 246, 0.04) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#0c0a09",
  },
  "warm-amber": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(245, 158, 11, 0.14) 0%, \n          rgba(245, 158, 11, 0.08) 25%, \n          rgba(245, 158, 11, 0.03) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#0f0f23",
  },
  "moonlight-silver": {
    backgroundImage:
      "\n        radial-gradient(circle at 50% 50%, \n          rgba(203, 213, 225, 0.12) 0%, \n          rgba(203, 213, 225, 0.07) 25%, \n          rgba(203, 213, 225, 0.03) 35%, \n          transparent 50%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#020617",
  },
  "center-spotlight-white": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(255, 255, 255, 0.08) 0%,\n          rgba(255, 255, 255, 0.04) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-blue": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(59, 130, 246, 0.12) 0%,\n          rgba(59, 130, 246, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-emerald": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(34, 197, 94, 0.12) 0%,\n          rgba(34, 197, 94, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-crimson": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(239, 68, 68, 0.12) 0%,\n          rgba(239, 68, 68, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-violet": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(168, 85, 247, 0.12) 0%,\n          rgba(168, 85, 247, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-amber": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(245, 158, 11, 0.12) 0%,\n          rgba(245, 158, 11, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-cyan": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(6, 182, 212, 0.12) 0%,\n          rgba(6, 182, 212, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight-rose": {
    backgroundImage:
      "\n        radial-gradient(\n          circle at center,\n          rgba(244, 63, 94, 0.12) 0%,\n          rgba(244, 63, 94, 0.06) 20%,\n          rgba(0, 0, 0, 0.0) 60%\n        )\n      ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "center-spotlight": {
    backgroundImage:
      "\n     radial-gradient(\n       circle at center,\n       rgba(255, 255, 255, 0.08) 0%,\n       rgba(255, 255, 255, 0.04) 20%,\n       rgba(0, 0, 0, 0.0) 60%\n     )\n   ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "top-spotlight": {
    backgroundImage:
      "\n     radial-gradient(\n       circle at top,\n       rgba(255, 255, 255, 0.08) 0%,\n       rgba(255, 255, 255, 0.08) 20%,\n       rgba(0, 0, 0, 0.0) 60%\n     )\n   ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "aurora-edge-glow": {
    backgroundImage:
      "\n     radial-gradient(ellipse 50% 100% at 10% 0%, rgba(226, 232, 240, 0.15), transparent 65%)\n   ",
    backgroundSize: "100% 100%",
    backgroundColor: "#000000",
  },
  "prismatic-aurora-burst": {
    background:
      "\n        radial-gradient(ellipse 120% 80% at 70% 20%, rgba(255, 20, 147, 0.15), transparent 50%),\n        radial-gradient(ellipse 100% 60% at 30% 10%, rgba(0, 255, 255, 0.12), transparent 60%),\n        radial-gradient(ellipse 90% 70% at 50% 0%, rgba(138, 43, 226, 0.18), transparent 65%),\n        radial-gradient(ellipse 110% 50% at 80% 30%, rgba(255, 215, 0, 0.08), transparent 40%),\n        #000000\n      ",
  },
  "cosmic-nebula": {
    background:
      "\n     radial-gradient(ellipse 110% 70% at 25% 80%, rgba(147, 51, 234, 0.12), transparent 55%),\n     radial-gradient(ellipse 130% 60% at 75% 15%, rgba(59, 130, 246, 0.10), transparent 65%),\n     radial-gradient(ellipse 80% 90% at 20% 30%, rgba(236, 72, 153, 0.14), transparent 50%),\n     radial-gradient(ellipse 100% 40% at 60% 70%, rgba(16, 185, 129, 0.08), transparent 45%),\n     #000000\n   ",
  },
  "stellar-mist": {
    background:
      "\n     radial-gradient(ellipse 140% 50% at 15% 60%, rgba(124, 58, 237, 0.11), transparent 48%),\n     radial-gradient(ellipse 90% 80% at 85% 25%, rgba(245, 101, 101, 0.09), transparent 58%),\n     radial-gradient(ellipse 120% 65% at 40% 90%, rgba(34, 197, 94, 0.13), transparent 52%),\n     radial-gradient(ellipse 100% 45% at 70% 5%, rgba(251, 191, 36, 0.07), transparent 42%),\n     radial-gradient(ellipse 80% 75% at 90% 80%, rgba(168, 85, 247, 0.10), transparent 55%),\n     #000000\n   ",
  },
};
